import pg from "pg";
import { randomUUID } from "crypto";

const { Pool } = pg;

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

async function seedProducts() {
  try {
    console.log("🌱 Starting product seed...");

    const productData = [
      // Coffee Category
      {
        name: "Kopiko Blanca TWIN",
        description: "2 sachets of premium instant coffee",
        category: "Coffee",
        price: 15.00,
        bulkPrice: 135.00,
        weight: "2x20g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-KOPIKO-BLANCA-TWIN",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Kopiko Brown TWIN",
        description: "2 sachets of robust brown coffee",
        category: "Coffee",
        price: 15.00,
        bulkPrice: 135.00,
        weight: "2x20g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-KOPIKO-BROWN-TWIN",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Kopiko Black TWIN",
        description: "2 sachets of strong black coffee",
        category: "Coffee",
        price: 15.00,
        bulkPrice: 135.00,
        weight: "2x20g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-KOPIKO-BLACK-TWIN",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Birch Tree Coffee 8g",
        description: "Individual sachet instant coffee",
        category: "Coffee",
        price: 5.00,
        bulkPrice: null,
        weight: "8g",
        stockStatus: "in-stock",
        quantity: 200,
        branch: "Main Branch",
        sku: "SKU-BIRCH-8G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Birch Tree Coffee 21g",
        description: "Premium instant coffee sachet",
        category: "Coffee",
        price: 15.00,
        bulkPrice: null,
        weight: "21g",
        stockStatus: "in-stock",
        quantity: 180,
        branch: "Main Branch",
        sku: "SKU-BIRCH-21G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Birch Tree Coffee 55g",
        description: "Large coffee sachet pack",
        category: "Coffee",
        price: 32.00,
        bulkPrice: null,
        weight: "55g",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-BIRCH-55G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Birch Tree Coffee 150g",
        description: "Family pack instant coffee",
        category: "Coffee",
        price: 75.00,
        bulkPrice: null,
        weight: "150g",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-BIRCH-150G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      // Baking Ingredients
      {
        name: "Graham (Crushed)",
        description: "Crushed graham for baking",
        category: "Baking Ingredients",
        price: 50.00,
        bulkPrice: null,
        weight: "200g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-GRAHAM-CRUSHED",
        image: "/images/dashboard/graham-crushed-v2.png",
      },
      {
        name: "Graham (Cracker)",
        description: "Graham cracker sheets",
        category: "Baking Ingredients",
        price: 45.00,
        bulkPrice: null,
        weight: "200g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-GRAHAM-CRACKER",
        image: "/images/dashboard/graham-crushed-v2.png",
      },
      {
        name: "All-Purpose Flour 1kg",
        description: "Premium baking flour",
        category: "Baking Ingredients",
        price: 35.00,
        bulkPrice: null,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-FLOUR-1KG",
        image: "/images/dashboard/all-purpose-flour-v2.png",
      },
      {
        name: "All-Purpose Flour 500g",
        description: "Medium pack baking flour",
        category: "Baking Ingredients",
        price: 18.00,
        bulkPrice: null,
        weight: "500g",
        stockStatus: "in-stock",
        quantity: 140,
        branch: "Main Branch",
        sku: "SKU-FLOUR-500G",
        image: "/images/dashboard/all-purpose-flour-v2.png",
      },
      {
        name: "All-Purpose Flour 250g",
        description: "Small pack baking flour",
        category: "Baking Ingredients",
        price: 9.00,
        bulkPrice: null,
        weight: "250g",
        stockStatus: "in-stock",
        quantity: 160,
        branch: "Main Branch",
        sku: "SKU-FLOUR-250G",
        image: "/images/dashboard/all-purpose-flour-v2.png",
      },
      {
        name: "Angel Evaporated Milk 410ml",
        description: "Rich evaporated milk for baking",
        category: "Baking Ingredients",
        price: 34.00,
        bulkPrice: null,
        weight: "410ml",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-ANGEL-EVAP",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Angel Krem Densada 410ml",
        description: "Sweetened condensed milk",
        category: "Baking Ingredients",
        price: 63.00,
        bulkPrice: null,
        weight: "410ml",
        stockStatus: "in-stock",
        quantity: 90,
        branch: "Main Branch",
        sku: "SKU-ANGEL-KREM",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      // Condiments - simplified list
      {
        name: "Ajinamoto 11g",
        description: "Monosodium glutamate seasoning",
        category: "Condiments",
        price: 5.00,
        bulkPrice: null,
        weight: "11g",
        stockStatus: "in-stock",
        quantity: 250,
        branch: "Main Branch",
        sku: "SKU-AJINA-11G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 24g",
        description: "Single sachet seasoning pack",
        category: "Condiments",
        price: 7.00,
        bulkPrice: null,
        weight: "24g",
        stockStatus: "in-stock",
        quantity: 200,
        branch: "Main Branch",
        sku: "SKU-AJINA-24G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 50g",
        description: "Regular seasoning pack",
        category: "Condiments",
        price: 15.00,
        bulkPrice: null,
        weight: "50g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-AJINA-50G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 100g",
        description: "Large seasoning pack",
        category: "Condiments",
        price: 28.00,
        bulkPrice: null,
        weight: "100g",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-AJINA-100G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 270g",
        description: "Family size seasoning",
        category: "Condiments",
        price: 70.00,
        bulkPrice: null,
        weight: "270g",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-AJINA-270G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 500g",
        description: "Large seasoning container",
        category: "Condiments",
        price: 130.00,
        bulkPrice: null,
        weight: "500g",
        stockStatus: "in-stock",
        quantity: 60,
        branch: "Main Branch",
        sku: "SKU-AJINA-500G",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Ajinamoto 1kg",
        description: "Bulk seasoning pack",
        category: "Condiments",
        price: 230.00,
        bulkPrice: null,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 40,
        branch: "Main Branch",
        sku: "SKU-AJINA-1KG",
        image: "/images/dashboard/ajinomoto-seasoning.png",
      },
      {
        name: "Cocomama Gata 200ml",
        description: "Coconut cream for cooking",
        category: "Condiments",
        price: 36.00,
        bulkPrice: null,
        weight: "200ml",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-COCOMAMA-200",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Cocomama Gata 400ml",
        description: "Large coconut cream container",
        category: "Condiments",
        price: 70.00,
        bulkPrice: null,
        weight: "400ml",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-COCOMAMA-400",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 12ml",
        description: "Premium seasoning sachet",
        category: "Condiments",
        price: 7.00,
        bulkPrice: null,
        weight: "12ml",
        stockStatus: "in-stock",
        quantity: 200,
        branch: "Main Branch",
        sku: "SKU-KNORR-12",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 130ml",
        description: "Liquid seasoning bottle",
        category: "Condiments",
        price: 70.00,
        bulkPrice: null,
        weight: "130ml",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-KNORR-130",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 250ml Liquid",
        description: "Premium liquid seasoning",
        category: "Condiments",
        price: 115.00,
        bulkPrice: null,
        weight: "250ml",
        stockStatus: "in-stock",
        quantity: 90,
        branch: "Main Branch",
        sku: "SKU-KNORR-250-LIQ",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 250ml Pouch",
        description: "Convenient seasoning pouch",
        category: "Condiments",
        price: 98.00,
        bulkPrice: null,
        weight: "250ml",
        stockStatus: "in-stock",
        quantity: 95,
        branch: "Main Branch",
        sku: "SKU-KNORR-250-POUCH",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 500ml",
        description: "Economy size seasoning",
        category: "Condiments",
        price: 165.00,
        bulkPrice: null,
        weight: "500ml",
        stockStatus: "in-stock",
        quantity: 70,
        branch: "Main Branch",
        sku: "SKU-KNORR-500",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Knorr Seasoning 1L",
        description: "Large seasoning bottle",
        category: "Condiments",
        price: 320.00,
        bulkPrice: null,
        weight: "1L",
        stockStatus: "low-stock",
        quantity: 30,
        branch: "Main Branch",
        sku: "SKU-KNORR-1L",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Magic Sarap 8g",
        description: "All-purpose seasoning sachet",
        category: "Condiments",
        price: 5.00,
        bulkPrice: null,
        weight: "8g",
        stockStatus: "in-stock",
        quantity: 250,
        branch: "Main Branch",
        sku: "SKU-MAGIC-8G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Magic Sarap 21g",
        description: "Standard seasoning pack",
        category: "Condiments",
        price: 15.00,
        bulkPrice: null,
        weight: "21g",
        stockStatus: "in-stock",
        quantity: 180,
        branch: "Main Branch",
        sku: "SKU-MAGIC-21G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Magic Sarap 55g",
        description: "Family size seasoning",
        category: "Condiments",
        price: 32.00,
        bulkPrice: null,
        weight: "55g",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-MAGIC-55G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Magic Sarap 150g",
        description: "Large seasoning container",
        category: "Condiments",
        price: 75.00,
        bulkPrice: null,
        weight: "150g",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-MAGIC-150G",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Datu Toyo 200ml",
        description: "Soy sauce bottle",
        category: "Condiments",
        price: 12.00,
        bulkPrice: null,
        weight: "200ml",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-DATU-TOYO-200",
        image: "/images/dashboard/datu-toyo.png",
      },
      {
        name: "Datu Toyo 385ml",
        description: "Regular soy sauce bottle",
        category: "Condiments",
        price: 25.00,
        bulkPrice: null,
        weight: "385ml",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-DATU-TOYO-385",
        image: "/images/dashboard/datu-toyo.png",
      },
      {
        name: "Datu Toyo 1L",
        description: "Family size soy sauce",
        category: "Condiments",
        price: 60.00,
        bulkPrice: null,
        weight: "1L",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-DATU-TOYO-1L",
        image: "/images/dashboard/datu-toyo.png",
      },
      {
        name: "Datu Suka 200ml",
        description: "Vinegar bottle",
        category: "Condiments",
        price: 10.00,
        bulkPrice: null,
        weight: "200ml",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-DATU-SUKA-200",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Datu Suka 385ml",
        description: "Regular vinegar bottle",
        category: "Condiments",
        price: 23.00,
        bulkPrice: null,
        weight: "385ml",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-DATU-SUKA-385",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Datu Suka 1L",
        description: "Family size vinegar",
        category: "Condiments",
        price: 50.00,
        bulkPrice: null,
        weight: "1L",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-DATU-SUKA-1L",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      // Household & Laundry Supplies
      {
        name: "Sunsilk Pink 15ml",
        description: "Premium shampoo sachet",
        category: "Household & Laundry Supplies",
        price: 8.00,
        bulkPrice: 80.00,
        weight: "15ml",
        stockStatus: "in-stock",
        quantity: 200,
        branch: "Main Branch",
        sku: "SKU-SUNSILK-15",
        image: "/images/dashboard/kopiko-blanca-twin-v2.png",
      },
      {
        name: "Maxglow Dishwashing 330ml",
        description: "Liquid dishwashing detergent",
        category: "Household & Laundry Supplies",
        price: 20.00,
        bulkPrice: 400.00,
        weight: "330ml",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-330",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      {
        name: "Maxglow Dishwashing 1L",
        description: "Economical liquid detergent",
        category: "Household & Laundry Supplies",
        price: 35.00,
        bulkPrice: 400.00,
        weight: "1L",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-1L",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      {
        name: "Maxglow Dishwashing 1.5L",
        description: "Large dishwashing detergent",
        category: "Household & Laundry Supplies",
        price: 50.00,
        bulkPrice: 400.00,
        weight: "1.5L",
        stockStatus: "in-stock",
        quantity: 80,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-1.5L",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      {
        name: "Maxglow Dishwashing 1 Gallon",
        description: "Bulk dishwashing detergent",
        category: "Household & Laundry Supplies",
        price: 135.00,
        bulkPrice: 535.00,
        weight: "1 Gallon",
        stockStatus: "in-stock",
        quantity: 40,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-GALLON",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      {
        name: "Maxglow Powder Pink 1kg",
        description: "Powdered laundry detergent",
        category: "Household & Laundry Supplies",
        price: 42.00,
        bulkPrice: 1000.00,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 90,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-POWDER-PINK",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      {
        name: "Maxglow Powder Blue 1kg",
        description: "Powdered laundry detergent",
        category: "Household & Laundry Supplies",
        price: 42.00,
        bulkPrice: 1000.00,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 90,
        branch: "Main Branch",
        sku: "SKU-MAXGLOW-POWDER-BLUE",
        image: "/images/dashboard/maxglow-dishwashing.png",
      },
      // Sauces
      {
        name: "Tomato Sauce Original 115g",
        description: "Pure tomato sauce",
        category: "Sauces",
        price: 22.00,
        bulkPrice: null,
        weight: "115g",
        stockStatus: "in-stock",
        quantity: 120,
        branch: "Main Branch",
        sku: "SKU-TOMATO-115",
        image: "/images/dashboard/tomato-sauce.png",
      },
      {
        name: "Tomato Sauce Original 200g",
        description: "Medium tomato sauce can",
        category: "Sauces",
        price: 26.00,
        bulkPrice: null,
        weight: "200g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-TOMATO-200",
        image: "/images/dashboard/tomato-sauce.png",
      },
      {
        name: "Tomato Sauce Original 250g",
        description: "Regular tomato sauce can",
        category: "Sauces",
        price: 30.00,
        bulkPrice: null,
        weight: "250g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-TOMATO-250",
        image: "/images/dashboard/tomato-sauce.png",
      },
      {
        name: "Tomato Sauce Original 900g",
        description: "Large tomato sauce can",
        category: "Sauces",
        price: 95.00,
        bulkPrice: null,
        weight: "900g",
        stockStatus: "in-stock",
        quantity: 60,
        branch: "Main Branch",
        sku: "SKU-TOMATO-900",
        image: "/images/dashboard/tomato-sauce.png",
      },
      {
        name: "Delmonte Party Pack 1kg Filipino",
        description: "Filipino-style tomato sauce party pack",
        category: "Sauces",
        price: 150.00,
        bulkPrice: null,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 50,
        branch: "Main Branch",
        sku: "SKU-DELMONTE-FILO",
        image: "/images/dashboard/tomato-sauce.png",
      },
      {
        name: "Delmonte Party Pack 1kg Sweets",
        description: "Sweet-style tomato sauce party pack",
        category: "Sauces",
        price: 150.00,
        bulkPrice: null,
        weight: "1kg",
        stockStatus: "in-stock",
        quantity: 50,
        branch: "Main Branch",
        sku: "SKU-DELMONTE-SWEET",
        image: "/images/dashboard/tomato-sauce.png",
      },
      // Canned Goods
      {
        name: "Ligo Sardines Red 425g",
        description: "Premium canned sardines in tomato sauce",
        category: "Canned Goods",
        price: 68.00,
        bulkPrice: null,
        weight: "425g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-LIGO-RED-425",
        image: "/images/dashboard/ligo-sardines-red.png",
      },
      {
        name: "Ligo Sardines Green 425g",
        description: "Canned sardines in brine",
        category: "Canned Goods",
        price: 67.00,
        bulkPrice: null,
        weight: "425g",
        stockStatus: "in-stock",
        quantity: 100,
        branch: "Main Branch",
        sku: "SKU-LIGO-GREEN-425",
        image: "/images/dashboard/ligo-sardines-red.png",
      },
      {
        name: "Ligo Sardines Red 155g",
        description: "Regular size red sardines",
        category: "Canned Goods",
        price: 28.00,
        bulkPrice: null,
        weight: "155g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-LIGO-RED-155",
        image: "/images/dashboard/ligo-sardines-red.png",
      },
      {
        name: "Ligo Sardines Green 155g",
        description: "Regular size green sardines",
        category: "Canned Goods",
        price: 28.00,
        bulkPrice: null,
        weight: "155g",
        stockStatus: "in-stock",
        quantity: 150,
        branch: "Main Branch",
        sku: "SKU-LIGO-GREEN-155",
        image: "/images/dashboard/ligo-sardines-red.png",
      },
    ];

    // Check if products table exists first
    const tableCheckResult = await pool.query(`
      SELECT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'products'
      );
    `);

    if (!tableCheckResult.rows[0].exists) {
      console.log("❌ Products table doesn't exist. Please run migrations first.");
      process.exit(1);
    }

    // Insert products
    let insertedCount = 0;
    for (const product of productData) {
      try {
        await pool.query(
          `INSERT INTO products 
          (id, name, description, category, price, bulk_price, weight, image, stock_status, quantity, branch, sku, is_active)
          VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)`,
          [
            randomUUID(),
            product.name,
            product.description,
            product.category,
            product.price,
            product.bulkPrice,
            product.weight,
            product.image,
            product.stockStatus,
            product.quantity,
            product.branch,
            product.sku,
            true,
          ]
        );
        insertedCount++;
      } catch (error) {
        if (error instanceof Error && error.message.includes("duplicate key")) {
          console.log(`⚠️  Skipping ${product.sku} (already exists)`);
        } else {
          throw error;
        }
      }
    }

    console.log(`✅ Successfully seeded ${insertedCount} products!`);
    await pool.end();
    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding products:", error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

seedProducts();
